COMP_hack: libcomp Namespace Reference
libcomp Namespace Reference
libcomp Includes
Namespaces
Compress
Routines to compress and decompress data using zlib.
Config
Convert
Crypto
Encryption and Decryption functions.
Message
Parsers
Platform
Shutdown
Classes
class ArgumentParser
Class to handle parsing command line arguments for an application.
class BaseServer
Base class for all servers that run workers to handle incoming messages in the message queue.
class BasicPacketStream
Abstract stream representing a data to be read from a packet.
class BinaryDataSet
class ChannelConnection
Represents a dedicated connection type for a channel server in charge of game client communication.
class Child
class Database
Abstract base class that represents a database to use for loading and modifying PersistentObject instances as well as utility tables by translating actions to database specific query syntax.
class DatabaseBind
Base class for binding database columns to allow quick access to getting and setting the associated column.
class DatabaseBindBigInt
64-bit integer column database binding by column name and value.
class DatabaseBindBlob
Blob column database binding by column name and value.
class DatabaseBindBool
Boolean column database binding by column name and value.
class DatabaseBindDouble
Double column database binding by column name and value.
class DatabaseBindFloat
Float column database binding by column name and value.
class DatabaseBindInt
32-bit integer column database binding by column name and value.
class DatabaseBindText
Text column database binding by column name and value.
class DatabaseBindUUID
UUID column database binding by column name and value.
class DatabaseChangeSet
Database change set grouped by a transaction UUID to be processed as one operation.
class DatabaseMariaDB
Represents a MariaDB database connection via the supplied config.
class DatabaseQuery
Database query wrapper class that contains a database specific query implementation so the pointer does not need to be worked with directly.
class DatabaseQueryImpl
Abstract base class to be implemented by specific database types to facilitate column binding and data retrieval.
class DatabaseQueryMariaDB
MariaDB database specific implementation of a query with binding and data retrieval functionality.
class DatabaseQuerySQLite3
SQLite3 database specific implementation of a query with binding and data retrieval functionality.
class DatabaseSQLite3
Represents a SQLite3 database connection associated to a specific file via the supplied config.
class DataFile
class DataStore
class DataSyncManager
Manager to synchronize data between two or more servers.
class DayCare
class DBExplicitUpdate
Explicit operational update to a record containing one or many field updates that are bound to match an expected "pre-update" value.
class DBOperationalChange
Represents a single operation that can be strung together with others to form a database agnostic complex query.
class DBOperationalChangeSet
Operational database change set consisting of inserts, updates, deletes or explicit updates which will be processed in the order they were added in.
class DBStandardChangeSet
Standard database change set consisting of inserts, updates or deletes which will be processed in that order, NOT the order they were added in.
class DefinitionManager
Manager class responsible for loading binary files that are accessible client side to use as server definitions.
class DynamicObject
Represents an object that can be built dynamically at runtime.
class DynamicVariable
Represents a variable that can be built dynamically at runtime.
class DynamicVariableArray
Represents an array variable that can be built dynamically at runtime.
class DynamicVariableFactory
Factory class used to build a DynamicVariable from a MetaVariable definition.
class DynamicVariableInt
Represents a numeric variable that can be built dynamically at runtime.
class DynamicVariableList
Represents a list variable that can be built dynamically at runtime.
class DynamicVariableReference
Represents a reference variable that can be built dynamically at runtime.
class DynamicVariableString
Represents a string variable that can be built dynamically at runtime.
class EncryptedConnection
Represents an encrypted network connection.
class EnumClassHash
Helper class to convert an enum value into its numeric representation so it can be used in sortable collections.
class Exception
Base exception class.
class InternalConnection
Represents a connection established between two internal servers.
class LobbyConnection
Represents a dedicated connection type for a lobby server in charge of game client authentication and communication prior to connecting to a world channel server.
class Log
Logging interface capable of logging messages to the terminal or a file.
class LogMessage
class LogMessageFixed
class LogMessageImpl
class Manager
Abstract base class used to represent a Message handler.
class ManagerPacket
Manager dedicated to handling messages of type libcomp::Message::Packet.
struct MemoryAllocation
A memory allocation contains the address, size, timestamp and a backtrace of where the memory was allocated.
class MemoryManager
This class will track memory allocations for later analysis.
class MessageQueue
A thread safe collection of Message instances to be created and handled by a server.
class Mutex
Mutex wrapper that checks if the mutex has already been locked.
class Object
Abstract base class that represents any object that can be defined via a MetaObject definition and corresonding value assignment that can be read via XML.
class ObjectInStream
A data input stream wrapper with collection type size information broken out into a seperate field.
class ObjectOutStream
A data output stream wrapper with collection type size information broken out into a seperate field.
class ObjectReference
Templated class that handles references to a PersistentObject derived class that can be lazy loaded from the database when needed.
class ObjectReferenceData
Represents a UUID and its associated PersistentObject that can either be loaded from the DB or pending loading from the DB.
class Packet
Convenience class to read and write packet data.
class PacketException
Exception in reading to or writing from a Packet object.
class PacketParser
Class responsible for parsing and handling packet.
class PacketStream
Stream representing data written to a packet to be read.
class PEFile
Wrapper class to aid in parsing a PE file.
class PersistentObject
Base class of a all dynamically generated objects that persist in the database.
class Randomizer
Static utility class used for improved random number generation.
class ReadOnlyPacket
Convenience class to read and write packet data.
class ReadOnlyPacketStream
Stream representing data written to a read only packet to be read.
class RingBuffer
Single producer, single consumer, lock free, no wait ring buffer.
class ScriptEngine
Represents a Sqrat based Squirrel virtual machine handler to facilitate script execution and bind Object instances to the VM.
class ServerCommandLineParser
Class to handle parsing command line arguments for a server.
class ServerConstants
Static Accessor class for the initalization and retrieval of ServerConstants::Data.
class ServerDataManager
Manager class responsible for loading server specific files such as zones and script files.
struct ServerScript
Container for script information.
class SpawnThread
class String
UTF-8 encoded string object.
class TcpConnection
Class to manage a TCP/IP connection.
class TcpServer
Listen for new TCP/IP connections.
class TimerEvent
class TimerEventComp
class TimerManager
class VectorStream
class WatchThread
class Worker
Generic worker assigned to a message queue used to handle messages as they are received.
Typedefs
typedef uint16_t CommandCode_t
template<typename Key , typename T >
using EnumMap = std::unordered_map< Key, T, HashType< Key >>
Replacement for map with a enum key type and a templated value.
template<typename Key , typename T >
using EnumMultiMap = std::unordered_multimap< Key, T, HashType< Key >>
Replacement for map with a enum key type and a templated value.
template<typename Key >
using HashType = typename std::conditional< std::is_enum< Key >::value, EnumClassHash, std::hash< Key >>::type
Validator that we are actually using an enum for the EnumMap.
Enumerations
enum LogComponent_t {
LogComponent_t::AccountManager, LogComponent_t::ActionManager, LogComponent_t::AIManager, LogComponent_t::Barter,
LogComponent_t::Bazaar, LogComponent_t::CharacterManager, LogComponent_t::ChatManager, LogComponent_t::Clan,
LogComponent_t::Connection, LogComponent_t::Crypto, LogComponent_t::Database, LogComponent_t::DataStore,
LogComponent_t::DataSyncManager, LogComponent_t::DefinitionManager, LogComponent_t::Demon, LogComponent_t::EventManager,
LogComponent_t::Friend, LogComponent_t::FusionManager, LogComponent_t::General, LogComponent_t::Invalid,
LogComponent_t::Item, LogComponent_t::MatchManager, LogComponent_t::Packet, LogComponent_t::Party,
LogComponent_t::ScriptEngine, LogComponent_t::Server, LogComponent_t::ServerConstants, LogComponent_t::ServerDataManager,
LogComponent_t::SkillManager, LogComponent_t::Team, LogComponent_t::TokuseiManager, LogComponent_t::Trade,
LogComponent_t::WebAPI, LogComponent_t::ZoneManager
}
Log components a log message may belong to.
Functions
template<>
bool DBExplicitUpdate::Set< libcomp::String > (const libcomp::String &column, libcomp::String value)
template<>
bool DBExplicitUpdate::Set< libobjgen::UUID > (const libcomp::String &column, libobjgen::UUID value)
template<>
bool DBExplicitUpdate::SetFrom< libcomp::String > (const libcomp::String &column, libcomp::String value, libcomp::String expected)
template<>
bool DBExplicitUpdate::SetFrom< libobjgen::UUID > (const libcomp::String &column, libobjgen::UUID value, libobjgen::UUID expected)
template<>
bool DefinitionManager::LoadData< objects::MiAIData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiBlendData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiBlendExtData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiCHouraiData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiCItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiCultureItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilBookData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilBoostData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilBoostExtraData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilBoostItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilBoostLotData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilEquipmentData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilEquipmentItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilFusionData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDevilLVUpRateData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDisassemblyData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDisassemblyTriggerData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiDynamicMapData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiEnchantData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiEquipmentSetData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiExchangeData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiExpertData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiGuardianAssistData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiGuardianLevelData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiGuardianSpecialData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiGuardianUnlockData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiHNPCData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiMissionData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiMitamaReunionBonusData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiMitamaReunionSetBonusData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiMitamaUnionBonusData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiModificationData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiModificationExtEffectData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiModificationExtRecipeData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiModificationTriggerData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiModifiedEffectData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiNPCBarterConditionData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiNPCBarterData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiNPCBarterGroupData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiONPCData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiQuestBonusCodeData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiQuestData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiShopProductData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiSItemData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiSkillData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiStatusData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiSynthesisData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiTankData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiTimeLimitData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiTitleData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiTriUnionSpecialData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiUraFieldTowerData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiWarpPointData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::LoadData< objects::MiZoneData > (gsl::not_null< DataStore * > pDataStore)
template<>
bool DefinitionManager::RegisterServerSideDefinition< objects::EnchantSetData > (const std::shared_ptr< objects::EnchantSetData > &record)
template<>
bool DefinitionManager::RegisterServerSideDefinition< objects::EnchantSpecialData > (const std::shared_ptr< objects::EnchantSpecialData > &record)
template<>
bool DefinitionManager::RegisterServerSideDefinition< objects::MiSItemData > (const std::shared_ptr< objects::MiSItemData > &record)
template<>
bool DefinitionManager::RegisterServerSideDefinition< objects::MiSStatusData > (const std::shared_ptr< objects::MiSStatusData > &record)
template<>
bool DefinitionManager::RegisterServerSideDefinition< objects::Tokusei > (const std::shared_ptr< objects::Tokusei > &record)
void GetMemoryStats (uint64_t &allocationCount, size_t &heapSize)
Gets basic statistics on the memory usage.
void InitMemoryManager ()
Initialize and enable the memory manager.
bool IsMemoryManagerEnabled ()
Check if the memory manager is enabled.
String LogComponentToString (LogComponent_t comp)
Convert a log component into a string.
template<>
ScriptEngine & ScriptEngine::Using< libobjgen::UUID > ()
template<>
ScriptEngine & ScriptEngine::Using< Sqrat::s64 > ()
template<>
ScriptEngine & ScriptEngine::Using< Sqrat::u64 > ()
template<>
bool ServerDataManager::LoadObject< objects::AILogicGroup > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::DemonFamiliarityType > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::DemonPresent > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::DemonQuestReward > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::DropSet > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::EnchantSetData > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::EnchantSpecialData > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::Event > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::MiSItemData > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::MiSStatusData > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::ServerShop > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::ServerZone > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::ServerZoneInstance > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::ServerZoneInstanceVariant > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::ServerZonePartial > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
template<>
bool ServerDataManager::LoadObject< objects::Tokusei > (const tinyxml2::XMLDocument &doc, const tinyxml2::XMLElement *objNode, DefinitionManager *definitionManager)
LogComponent_t StringToLogComponent (const String &comp)
Convert a string into a log component.
void TriggerMemorySnapshot ()
Trigger a memory snapshot.
Variables
const std::size_t BLOWFISH_BLOCK_SIZE = sizeof(uint64_t)
Size (in bytes) of a block of Blowfish encrypted data.
static std::set
< libobjgen::MetaVariable::MetaVariableType_t > validInt32Types
static std::set
< libobjgen::MetaVariable::MetaVariableType_t > validInt64Types
Detailed Description
libcomp Includes
Standard C++11 Includes.
Typedef Documentation
typedef uint16_t libcomp::CommandCode_t
Definition at line 42 of file ManagerPacket.h.
template<typename Key , typename T > using libcomp::EnumMap = typedef std::unordered_map<Key, T, HashType<Key>>
Replacement for map with a enum key type and a templated value.
Definition at line 68 of file EnumMap.h.
template<typename Key , typename T > using libcomp::EnumMultiMap = typedef std::unordered_multimap<Key, T, HashType<Key>>
Replacement for map with a enum key type and a templated value.
Definition at line 74 of file EnumMap.h.
template<typename Key > using libcomp::HashType = typedef typename std::conditional<std::is_enum<Key>::value, EnumClassHash, std::hash<Key>>::type
Validator that we are actually using an enum for the EnumMap.
Definition at line 62 of file EnumMap.h.
Enumeration Type Documentation
enum libcomp::LogComponent_t strong
Log components a log message may belong to.
Enumerator
AccountManager
ActionManager
AIManager
Barter
Bazaar
CharacterManager
ChatManager
Clan
Connection
Crypto
Database
DataStore
DataSyncManager
DefinitionManager
Demon
EventManager
Friend
FusionManager
General
Invalid
Item
MatchManager
Packet
Party
ScriptEngine
Server
ServerConstants
ServerDataManager
SkillManager
Team
TokuseiManager
Trade
WebAPI
ZoneManager
Definition at line 48 of file Log.h.
Function Documentation
template<> bool libcomp::DBExplicitUpdate::Set< libcomp::String > (const libcomp::String & column, libcomp::String value)
Definition at line 466 of file DatabaseChangeSet.cpp.
template<> bool libcomp::DBExplicitUpdate::Set< libobjgen::UUID > (const libcomp::String & column, libobjgen::UUID value)
Definition at line 497 of file DatabaseChangeSet.cpp.
template<> bool libcomp::DBExplicitUpdate::SetFrom< libcomp::String > (const libcomp::String & column, libcomp::String value, libcomp::String expected)
Definition at line 457 of file DatabaseChangeSet.cpp.
template<> bool libcomp::DBExplicitUpdate::SetFrom< libobjgen::UUID > (const libcomp::String & column, libobjgen::UUID value, libobjgen::UUID expected)
Definition at line 488 of file DatabaseChangeSet.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiAIData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 816 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiBlendData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 831 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiBlendExtData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 846 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiCHouraiData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 861 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiCItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 876 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiCultureItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 896 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilBookData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 911 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilBoostData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 926 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilBoostExtraData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 941 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilBoostItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 956 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilBoostLotData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 971 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 987 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilEquipmentData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1030 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilEquipmentItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1045 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilFusionData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1060 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDevilLVUpRateData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1084 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDisassemblyData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1099 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDisassemblyTriggerData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1130 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiDynamicMapData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1147 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::LoadData< objects::MiEnchantData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1200 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::LoadData< objects::MiEquipmentSetData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1248 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiExchangeData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1277 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiExpertData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1292 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiGuardianAssistData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1307 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiGuardianLevelData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1322 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiGuardianSpecialData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1337 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiGuardianUnlockData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1352 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiHNPCData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1367 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1382 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiMissionData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1397 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiMitamaReunionBonusData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1412 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiMitamaReunionSetBonusData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1427 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiMitamaUnionBonusData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1442 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiModificationData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1457 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::LoadData< objects::MiModificationExtEffectData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1488 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiModificationExtRecipeData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1506 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::LoadData< objects::MiModificationTriggerData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1541 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiModifiedEffectData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1557 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiNPCBarterConditionData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1587 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiNPCBarterData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1572 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiNPCBarterGroupData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1604 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiONPCData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1619 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiQuestBonusCodeData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1634 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiQuestData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1649 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiShopProductData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1664 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiSItemData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1679 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiSkillData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1701 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiStatusData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1724 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiSynthesisData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1739 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiTankData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1754 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiTimeLimitData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1769 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiTitleData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1784 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiTriUnionSpecialData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1808 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiUraFieldTowerData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1833 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiWarpPointData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1848 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::LoadData< objects::MiZoneData > (gsl::not_null< DataStore * > pDataStore)
Definition at line 1863 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::RegisterServerSideDefinition< objects::EnchantSetData > (const std::shared_ptr< objects::EnchantSetData > & record)
Definition at line 1956 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::RegisterServerSideDefinition< objects::EnchantSpecialData > (const std::shared_ptr< objects::EnchantSpecialData > & record)
Definition at line 1985 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::RegisterServerSideDefinition< objects::MiSItemData > (const std::shared_ptr< objects::MiSItemData > & record)
Definition at line 2006 of file DefinitionManager.cpp.
template<> bool libcomp::DefinitionManager::RegisterServerSideDefinition< objects::MiSStatusData > (const std::shared_ptr< objects::MiSStatusData > & record)
Definition at line 2024 of file DefinitionManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::DefinitionManager::RegisterServerSideDefinition< objects::Tokusei > (const std::shared_ptr< objects::Tokusei > & record)
Definition at line 2044 of file DefinitionManager.cpp.
References libcomp::String::Arg().
void libcomp::GetMemoryStats (uint64_t & allocationCount, size_t & heapSize)
Gets basic statistics on the memory usage.
Parameters
allocationCount How many blocks of memory are allocated.
heapSize Size of the heap in bytes (size of all allocations).
Definition at line 105 of file MemoryManager.cpp.
References libcomp::MemoryManager::GetStats(), and gManager.
void libcomp::InitMemoryManager ()
Initialize and enable the memory manager.
Definition at line 90 of file MemoryManager.cpp.
References gManager, gMemoryManagerEnabled, and libcomp::MemoryManager::Setup().
Referenced by libcomp::BaseServer::ReadConfig().
bool libcomp::IsMemoryManagerEnabled ()
Check if the memory manager is enabled.
Returns
true if the memory manager is enabled; false otherwise.
Definition at line 85 of file MemoryManager.cpp.
References gMemoryManagerEnabled.
Referenced by libcomp::Exception::Exception().
String libcomp::LogComponentToString (LogComponent_t comp)
Convert a log component into a string.
Parameters
comp Log component to convert.
Returns
String representation of the log component.
Definition at line 147 of file Log.cpp.
References General, and gLogComponentMapping.
Referenced by libcomp::Log::LogMessage().
template<> ScriptEngine& libcomp::ScriptEngine::Using< libobjgen::UUID > ()
Definition at line 381 of file PersistentObject.cpp.
template<> ScriptEngine& libcomp::ScriptEngine::Using< Sqrat::s64 > ()
Definition at line 697 of file SqratInt64.cpp.
References Sqrat::s64::_add(), Sqrat::s64::_cmp(), Sqrat::s64::_div(), Sqrat::s64::_mod(), Sqrat::s64::_mul(), Sqrat::s64::_sub(), Sqrat::s64::_tostring(), Sqrat::s64::equal(), s64_cast(), and Sqrat::s64::valueTruncated().
template<> ScriptEngine& libcomp::ScriptEngine::Using< Sqrat::u64 > ()
Definition at line 720 of file SqratInt64.cpp.
References Sqrat::u64::_add(), Sqrat::u64::_cmp(), Sqrat::u64::_div(), Sqrat::u64::_mod(), Sqrat::u64::_mul(), Sqrat::u64::_sub(), Sqrat::u64::_tostring(), Sqrat::u64::equal(), u64_cast(), and Sqrat::u64::valueTruncated().
template<> bool libcomp::ServerDataManager::LoadObject< objects::AILogicGroup > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1526 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::DemonFamiliarityType > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1555 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::DemonPresent > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1585 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::DemonQuestReward > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1614 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::DropSet > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1643 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::EnchantSetData > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1723 of file ServerDataManager.cpp.
template<> bool libcomp::ServerDataManager::LoadObject< objects::EnchantSpecialData > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1736 of file ServerDataManager.cpp.
template<> bool libcomp::ServerDataManager::LoadObject< objects::Event > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1230 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::MiSItemData > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1749 of file ServerDataManager.cpp.
template<> bool libcomp::ServerDataManager::LoadObject< objects::MiSStatusData > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1762 of file ServerDataManager.cpp.
template<> bool libcomp::ServerDataManager::LoadObject< objects::ServerShop > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1481 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::ServerZone > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 907 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::ServerZoneInstance > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1277 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::ServerZoneInstanceVariant > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1347 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::ServerZonePartial > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1093 of file ServerDataManager.cpp.
References libcomp::String::Arg().
template<> bool libcomp::ServerDataManager::LoadObject< objects::Tokusei > (const tinyxml2::XMLDocument & doc, const tinyxml2::XMLElement * objNode, DefinitionManager * definitionManager)
Definition at line 1775 of file ServerDataManager.cpp.
LogComponent_t libcomp::StringToLogComponent (const String & comp)
Convert a string into a log component.
Parameters
comp String to convert.
Returns
Log component the string represents.
Definition at line 134 of file Log.cpp.
References gLogComponentMapping, and Invalid.
Referenced by libcomp::BaseServer::ReadConfig().
void libcomp::TriggerMemorySnapshot ()
Trigger a memory snapshot.
Definition at line 97 of file MemoryManager.cpp.
References gManager, and libcomp::MemoryManager::Snapshot().
Variable Documentation
const std::size_t libcomp::BLOWFISH_BLOCK_SIZE = sizeof(uint64_t)
Size (in bytes) of a block of Blowfish encrypted data.
Definition at line 42 of file Crypto.h.
Referenced by libcomp::Crypto::Blowfish::Decrypt(), libcomp::Crypto::Blowfish::DecryptCbc(), libcomp::Crypto::Blowfish::Encrypt(), libcomp::Crypto::Blowfish::EncryptCbc(), libcomp::Crypto::Blowfish::EncryptPacket(), and libcomp::ChannelConnection::PreparePackets().
std::set<libobjgen::MetaVariable::MetaVariableType_t> libcomp::validInt32Types static
Initial value:
=
    {
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_S8,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_S16,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_S32,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_U8,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_U16
    }
Definition at line 266 of file DatabaseChangeSet.cpp.
Referenced by libcomp::DBExplicitUpdate::Add(), libcomp::DBExplicitUpdate::AddFrom(), libcomp::DBExplicitUpdate::Set(), libcomp::DBExplicitUpdate::SetFrom(), libcomp::DBExplicitUpdate::Subtract(), and libcomp::DBExplicitUpdate::SubtractFrom().
std::set<libobjgen::MetaVariable::MetaVariableType_t> libcomp::validInt64Types static
Initial value:
=
    {
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_S64,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_U32,
        libobjgen::MetaVariable::MetaVariableType_t::TYPE_U64
    }
Definition at line 317 of file DatabaseChangeSet.cpp.
Referenced by libcomp::DBExplicitUpdate::Add(), libcomp::DBExplicitUpdate::AddFrom(), libcomp::DBExplicitUpdate::Set(), libcomp::DBExplicitUpdate::SetFrom(), libcomp::DBExplicitUpdate::Subtract(), and libcomp::DBExplicitUpdate::SubtractFrom().